### ISSUE TITLE
Improve correctness and clarity of relative URLs for update subscriptions

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-spec#182]
https://github.com/solid/solid-spec/pull/181#issuecomment-496858494
https://github.com/solid/solid-spec/pull/181#issuecomment-496931430

**Comment by michielbdejong** [comment]
OK, hadn't realised this would trigger a discussion, sorry. I though from the phrasing 'Some implementations do X' it was clear that this was not something the spec prescribes, just a footnote, but this was obviously not clear, apologies. I do want to write down somewhere that NSS does something different from what the spec prescribes, but maybe it's better to keep it outside the spec itself, and just create a github issue about it on the NSS repo

**Comment by RubenVerborgh** [comment]
> I do want to write down somewhere that NSS does something different from what the spec prescribes

We should just determine what is right: should relative URLs be supported or not?
If yes, let's update the spec precisely; if no, NSS needs updating.

**Comment by michielbdejong** [comment]
Created https://github.com/solid/node-solid-ws/issues/11 about updating NSS.

Sorry again for the confusion about process, I had intended this as just adding a remark in the margin, not changing the prescriptive text itself, that's why I hadn't looked for broader consensus on the text of my remark. Now that it's become clear that multiple people interpreted it as more than just a passing comment, I fully agree that both the process and the result went wrong here. Thanks for flagging it!
