### ISSUE TITLE
defaultForNew confusing name

### ISSUE THREAD

**Issue by sandhawke** [solid/solid-spec#77]
The name "defaultForNew" has a plain English meaning which disagrees with the stated semantics, and believe the implemented semantics.

Test case would be: create a container with public defaultForNew, post to create p1, then change the container to have defaultForNew private.    If it were really "default for new" then p1 would still be public.  I don't think that's the case.

Suggested fix: renamed it to "background".

(Also, in Nicola's writeup at https://github.com/solid/solid-spec/blob/master/acl-inheritance.md what's called "default" should be called "union", I believe.   But since no one's implementing it, it may not matter.    One might also define "max" and "min" on containers that limit the flexibility of the children, if one wanted to have overrides at the folder level.)

**Comment by melvincarvalho** [comment]
Is this a suggestion to change the name, or to improve the definition, or to discuss further and clarify?

Given that this is already deployed, there is a higher cost associated with name changes, rather than, a lower cost to description changes (not that im arguing that cost isnt justified).  

I'll note sometimes names are not perfectly intuitive, but still work, for example "umask" in UNIX.

**Comment by sandhawke** [comment]
It's a request to change either the name or the semantics.   But I realize I put this on the wrong repo.   Closing and moving it.
